spring:
  application:
    name: example
  web:
    resources:
      add-mappings: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  servlet:
#    context-path: /api/v1
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.cache: trace